name: Create release JIRA task
description: "A GitHub Action to create release Jira task"
branding:
  icon: "git-pull-request"
  color: purple
inputs:
  github-token:
    description: "Token for GitHub access"
    required: true
  projectName:
    description: "Xcode pbxprodj file name"
    required: true
  versionPrefix:
    description: "It will be appended before version"
    required: true
  sourceBranch:
    description: "Branch name to compare from [default: Master]"
    required: true
  jiraAccount:
    description: "Jira account"
    required: true
  jiraToken:
    description: "Jira access token"
    required: true
  jiraHost:
    description: "Jira Host"
    required: true
    default: "https://taxify.atlassian.net"
  jiraProjectId:
    description: "Id of Jira Projects where to create release version and ticket \"1111\""
    required: true
  jiraTaskTypeId:
    description: "Id of Jira task type to create ticket with \"22222\""
    required: true
  jiraTaskAssigneeId:
    description: "Id of Jira user to use as Assignee"
    required: true
  jiraTaskComponentId:
    description: "Id for Jira component field"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
